[package]
name = "dayhelper-desktop-adapter-wayland"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
dayhelper-desktop-domain = { workspace = true }
dayhelper-desktop-ports = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
wayland-client = { workspace = true }
wayland-protocols = { workspace = true }
wayland-protocols-wlr = { workspace = true }
