[package]
name = "dayhelper-adapter-system"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
dayhelper-domain = { workspace = true }
dayhelper-ports = { workspace = true }
rand = { workspace = true }
