[package]
name = "dayhelper-server-desktop-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
dayhelper-application = { workspace = true }
dayhelper-domain = { workspace = true }
dayhelper-ports = { workspace = true }
dayhelper-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
